// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgZeqivsnT-QapzHIIK7AIdoR8hpHXB58',
    appId: '1:941972010123:android:ecf8ad85beed5b34db908e',
    messagingSenderId: '941972010123',
    projectId: 'hur-app',
    storageBucket: 'hur-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiMOV2jSBahi40sG9Yezs2zO-eGtFNS6Y',
    appId: '1:941972010123:ios:a9e44863cbdae9d5db908e',
    messagingSenderId: '941972010123',
    projectId: 'hur-app',
    storageBucket: 'hur-app.firebasestorage.app',
    iosClientId: '941972010123-349n3ilk73s8tktqopap46tqgasgsgam.apps.googleusercontent.com',
    iosBundleId: 'com.hur.hurDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgZeqivsnT-QapzHIIK7AIdoR8hpHXB58',
    appId: '1:941972010123:ios:ecf8ad85beed5b34db908e',
    messagingSenderId: '941972010123',
    projectId: 'hur-app',
    storageBucket: 'hur-app.firebasestorage.app',
    iosBundleId: 'com.hur.delivery',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATRWSTYX5z8V03PGslWDmvyNX6YdpTiZA',
    appId: '1:941972010123:web:bf354a7f981a8538db908e',
    messagingSenderId: '941972010123',
    projectId: 'hur-app',
    authDomain: 'hur-app.firebaseapp.com',
    storageBucket: 'hur-app.firebasestorage.app',
    measurementId: 'G-F8G7LJTBFW',
  );

}